/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as OnboardingGetStartedRouteImport } from './routes/_onboarding/get-started'
import { Route as AppServicesServiceIdRouteRouteImport } from './routes/_app/services/$serviceId/route'
import { Route as AppServicesServiceIdSettingsRouteImport } from './routes/_app/services/$serviceId/settings'
import { Route as AppServicesServiceIdOverviewRouteImport } from './routes/_app/services/$serviceId/overview'
import { Route as AppServicesServiceIdLogsRouteImport } from './routes/_app/services/$serviceId/logs'
import { Route as AppServicesServiceIdErrorsRouteImport } from './routes/_app/services/$serviceId/errors'
import { Route as AppServicesServiceIdEndpointsRouteImport } from './routes/_app/services/$serviceId/endpoints'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const OnboardingGetStartedRoute = OnboardingGetStartedRouteImport.update({
  id: '/_onboarding/get-started',
  path: '/get-started',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServicesServiceIdRouteRoute =
  AppServicesServiceIdRouteRouteImport.update({
    id: '/services/$serviceId',
    path: '/services/$serviceId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppServicesServiceIdSettingsRoute =
  AppServicesServiceIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppServicesServiceIdRouteRoute,
  } as any)
const AppServicesServiceIdOverviewRoute =
  AppServicesServiceIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AppServicesServiceIdRouteRoute,
  } as any)
const AppServicesServiceIdLogsRoute =
  AppServicesServiceIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => AppServicesServiceIdRouteRoute,
  } as any)
const AppServicesServiceIdErrorsRoute =
  AppServicesServiceIdErrorsRouteImport.update({
    id: '/errors',
    path: '/errors',
    getParentRoute: () => AppServicesServiceIdRouteRoute,
  } as any)
const AppServicesServiceIdEndpointsRoute =
  AppServicesServiceIdEndpointsRouteImport.update({
    id: '/endpoints',
    path: '/endpoints',
    getParentRoute: () => AppServicesServiceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/get-started': typeof OnboardingGetStartedRoute
  '/services/$serviceId': typeof AppServicesServiceIdRouteRouteWithChildren
  '/services/$serviceId/endpoints': typeof AppServicesServiceIdEndpointsRoute
  '/services/$serviceId/errors': typeof AppServicesServiceIdErrorsRoute
  '/services/$serviceId/logs': typeof AppServicesServiceIdLogsRoute
  '/services/$serviceId/overview': typeof AppServicesServiceIdOverviewRoute
  '/services/$serviceId/settings': typeof AppServicesServiceIdSettingsRoute
}
export interface FileRoutesByTo {
  '/get-started': typeof OnboardingGetStartedRoute
  '/': typeof AppIndexRoute
  '/services/$serviceId': typeof AppServicesServiceIdRouteRouteWithChildren
  '/services/$serviceId/endpoints': typeof AppServicesServiceIdEndpointsRoute
  '/services/$serviceId/errors': typeof AppServicesServiceIdErrorsRoute
  '/services/$serviceId/logs': typeof AppServicesServiceIdLogsRoute
  '/services/$serviceId/overview': typeof AppServicesServiceIdOverviewRoute
  '/services/$serviceId/settings': typeof AppServicesServiceIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_onboarding/get-started': typeof OnboardingGetStartedRoute
  '/_app/': typeof AppIndexRoute
  '/_app/services/$serviceId': typeof AppServicesServiceIdRouteRouteWithChildren
  '/_app/services/$serviceId/endpoints': typeof AppServicesServiceIdEndpointsRoute
  '/_app/services/$serviceId/errors': typeof AppServicesServiceIdErrorsRoute
  '/_app/services/$serviceId/logs': typeof AppServicesServiceIdLogsRoute
  '/_app/services/$serviceId/overview': typeof AppServicesServiceIdOverviewRoute
  '/_app/services/$serviceId/settings': typeof AppServicesServiceIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/get-started'
    | '/services/$serviceId'
    | '/services/$serviceId/endpoints'
    | '/services/$serviceId/errors'
    | '/services/$serviceId/logs'
    | '/services/$serviceId/overview'
    | '/services/$serviceId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/get-started'
    | '/'
    | '/services/$serviceId'
    | '/services/$serviceId/endpoints'
    | '/services/$serviceId/errors'
    | '/services/$serviceId/logs'
    | '/services/$serviceId/overview'
    | '/services/$serviceId/settings'
  id:
    | '__root__'
    | '/_app'
    | '/_onboarding/get-started'
    | '/_app/'
    | '/_app/services/$serviceId'
    | '/_app/services/$serviceId/endpoints'
    | '/_app/services/$serviceId/errors'
    | '/_app/services/$serviceId/logs'
    | '/_app/services/$serviceId/overview'
    | '/_app/services/$serviceId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  OnboardingGetStartedRoute: typeof OnboardingGetStartedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_onboarding/get-started': {
      id: '/_onboarding/get-started'
      path: '/get-started'
      fullPath: '/get-started'
      preLoaderRoute: typeof OnboardingGetStartedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/services/$serviceId': {
      id: '/_app/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof AppServicesServiceIdRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/services/$serviceId/settings': {
      id: '/_app/services/$serviceId/settings'
      path: '/settings'
      fullPath: '/services/$serviceId/settings'
      preLoaderRoute: typeof AppServicesServiceIdSettingsRouteImport
      parentRoute: typeof AppServicesServiceIdRouteRoute
    }
    '/_app/services/$serviceId/overview': {
      id: '/_app/services/$serviceId/overview'
      path: '/overview'
      fullPath: '/services/$serviceId/overview'
      preLoaderRoute: typeof AppServicesServiceIdOverviewRouteImport
      parentRoute: typeof AppServicesServiceIdRouteRoute
    }
    '/_app/services/$serviceId/logs': {
      id: '/_app/services/$serviceId/logs'
      path: '/logs'
      fullPath: '/services/$serviceId/logs'
      preLoaderRoute: typeof AppServicesServiceIdLogsRouteImport
      parentRoute: typeof AppServicesServiceIdRouteRoute
    }
    '/_app/services/$serviceId/errors': {
      id: '/_app/services/$serviceId/errors'
      path: '/errors'
      fullPath: '/services/$serviceId/errors'
      preLoaderRoute: typeof AppServicesServiceIdErrorsRouteImport
      parentRoute: typeof AppServicesServiceIdRouteRoute
    }
    '/_app/services/$serviceId/endpoints': {
      id: '/_app/services/$serviceId/endpoints'
      path: '/endpoints'
      fullPath: '/services/$serviceId/endpoints'
      preLoaderRoute: typeof AppServicesServiceIdEndpointsRouteImport
      parentRoute: typeof AppServicesServiceIdRouteRoute
    }
  }
}

interface AppServicesServiceIdRouteRouteChildren {
  AppServicesServiceIdEndpointsRoute: typeof AppServicesServiceIdEndpointsRoute
  AppServicesServiceIdErrorsRoute: typeof AppServicesServiceIdErrorsRoute
  AppServicesServiceIdLogsRoute: typeof AppServicesServiceIdLogsRoute
  AppServicesServiceIdOverviewRoute: typeof AppServicesServiceIdOverviewRoute
  AppServicesServiceIdSettingsRoute: typeof AppServicesServiceIdSettingsRoute
}

const AppServicesServiceIdRouteRouteChildren: AppServicesServiceIdRouteRouteChildren =
  {
    AppServicesServiceIdEndpointsRoute: AppServicesServiceIdEndpointsRoute,
    AppServicesServiceIdErrorsRoute: AppServicesServiceIdErrorsRoute,
    AppServicesServiceIdLogsRoute: AppServicesServiceIdLogsRoute,
    AppServicesServiceIdOverviewRoute: AppServicesServiceIdOverviewRoute,
    AppServicesServiceIdSettingsRoute: AppServicesServiceIdSettingsRoute,
  }

const AppServicesServiceIdRouteRouteWithChildren =
  AppServicesServiceIdRouteRoute._addFileChildren(
    AppServicesServiceIdRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppServicesServiceIdRouteRoute: typeof AppServicesServiceIdRouteRouteWithChildren
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppServicesServiceIdRouteRoute: AppServicesServiceIdRouteRouteWithChildren,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  OnboardingGetStartedRoute: OnboardingGetStartedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
